### ISSUE TITLE
Build/package.json

### ISSUE THREAD

**Issue by stroborobo** [Bixie/pagekit-formmaker#10]
Hey Bixie team :)

How do I build this project? `npm install -g webpack && webpack`? Unfortunately this fails since you're using some node modules that I don't have installed and there is no package.json in your repo, so I don't know which ones there are. I'll go by try and error now, but some building instructions would be great ;)

Have a good one!

**Comment by stroborobo** [comment]
Got this now:

```json
{
  "name": "pagekit-formmaker",
  "dependencies": {
    "babel-core": "^6.5.1",
    "babel-loader": "^6.2.2",
    "babel-plugin-transform-runtime": "^6.5.0",
    "babel-preset-es2015": "^6.5.0",
    "babel-runtime": "^5.8.0",
    "css-loader": "^0.23.1",
    "glob": "^7.0.0",
    "vue-hot-reload-api": "^1.3.2",
    "vue-html-loader": "^1.1.0",
    "vue-loader": "^8.1.1",
    "vue-style-loader": "^1.0.0",
    "webpack": "^1.12.13"
  }
}
```

All webpack complains about now is the camelCasing in `fieldtypes/textbox/textbox.vue`

**Comment by stroborobo** [comment]
While we're at it, wouldn't it be nicer to not have the built files (bundle) in the repo? IMHO they don't belong here. If I change things and rebuild them they kinda pollute the commit message. Also they contain local file paths that are only valid on one of your machines.

**Comment by malles** [comment]
THis package needs to be used in developed within a Pagekit environment, and has no build tools of its own.
The `webpack.config.js` file is read and executed by the global webpack job of Pagekit.
Install and build Pagekit from their Git repo, install this package via Marketplace or Package manager (or cli if you want to go cool). Running `webpack --watch` from the Pagekit root will also package the app of this extension.

**Comment by stroborobo** [comment]
I see, thanks!
