### ISSUE TITLE
File upload field

### ISSUE THREAD

**Issue by stroborobo** [Bixie/pagekit-formmaker#11]
Hey there,

so I was looking into implementing file upload fields, but I guess that wouldn't be possible without major changes, huh? `Bixie\Formmaker\Model\Form` needs to be `JsonSerializable`, but serialising binary would mean that we'd need special meta data per value to differentiate from normal strings. Can you confirm that?

**Comment by malles** [comment]
As said in #9, you can create own fieldtypes soon. An upload fieldtype would make sense to include in the core.
You won't save the binary string in the database, just the path to the file on the server.

**Comment by stroborobo** [comment]
> You won't save the binary string in the database, just the path to the file on the server.

Of course, but you're sending form data via JSON right now which doesn't work with binary data. So either you'd add a new Controller handling file uploads exclusively or add meta data to the base64 encoded binary in JSON so it's recognisable as binary. Just my thoughts since the fieldtypes don't seem like they can be more than fancy frontend, but no backend logic (right now). Or am I wrong?

Would you place the uploads into a subdirectory in storage or somewhere else?

**Comment by malles** [comment]
Yeah, the actual upload process would have it's own api endpoint. Preferably via the pagekit finder. That would return path and possibly thumb that would be stored as form-values. 
But you're right, that would need an extra backend hook for the upload. That hook can be provided by your own extension as well, so your custom fieldtype could use that.

**Comment by stroborobo** [comment]
I'm very new to all this, so maybe I miunderstood, but doesn't the Finder only work in the admin area?

**Comment by malles** [comment]
I was hoping to use the api-url anyway. But that didn't work indeed.
I've created the uploadfield in the framework, so it will be available in upcoming versions.
https://github.com/Bixie/pagekit-framework/commit/adc29aa2140bb428c66024175d50053f287bbf20

**Comment by stroborobo** [comment]
Great! We've implemented it ourself yesterday evening, but it's very hacky since it needed to be done quickly. (Polish later, yeah, I hate this too.) I'll have a look at your solution, thank you very much for this :)

**Comment by stroborobo** [comment]
Works well, thank you :)
