### ISSUE TITLE
Html code field breaking submission views

### ISSUE THREAD

**Issue by benedu** [Bixie/pagekit-formmaker#12]
Hello,

we have included a html code field into our form and everything is working as expected. Unfortunately the the html code fields are breaking the submissions views. See my attached picture of the bug:

![auswahl_041](https://cloud.githubusercontent.com/assets/14878247/13280127/7d5b2108-dadc-11e5-9c1d-9005610a44ef.png)

Seems like the html code will be parsed as text.

**Comment by malles** [comment]
This has been fixed in the current development branch. Thanks for reporting.
