### ISSUE TITLE
Custom HTML code

### ISSUE THREAD

**Issue by benedu** [Bixie/pagekit-formmaker#17]
Hey,

what do you think about custom HTML code for the form fields. So that one can insert some custom html at the beginning or end of the form row.

For example to show some help text to the user etc.

**Comment by malles** [comment]
The html code field type is meant for that. It gives you the possibility to print HTML text in the forms. Also see the text above date of birth in [the demo form](http://formmaker.bixie.org/demo-2).

I am thinking of creating a possibility for a help-text in a field with an info-icon and tooltip.

**Comment by benedu** [comment]
Well sounds like an good idea :) 

I just came around because I used the stacked form design and my label was like 3 lines long. With the html code field type it automatically insert a new row and therefore my help text had too much margin to the corresponding input.

Keep up your good work!

**Comment by malles** [comment]
I've created the field help text. You can put html in there and show it below the field, or have it as a tooltip.

https://github.com/Bixie/pagekit-framework/commit/1724b28d9b8e706b1b7175e1b4291c8b3516686d
