### ISSUE TITLE
Page integration

### ISSUE THREAD

**Issue by miniMAC** [Bixie/pagekit-formmaker#2]
Hello, is it possible to add a form inside a page?

**Comment by malles** [comment]
Not yet.
I will be making a widget for a form and the possibility to add a tag like `[formmaker id="1"]` to your page.

**Comment by malles** [comment]
The other way around is already possible, with the field type html code, you can add markup to your form.

**Comment by malles** [comment]
That's why I love Pagekit! I had some refactoring to do, but the plugin part was done in ten minutes.
Pagekit has default syntax for this: `(formmaker){"id":"1", "hide_title":"1"}` it will be.
It will be in the next update

**Comment by miniMAC** [comment]
Perfect! Thanks!
