### ISSUE TITLE
Passing ajax_url from back to front end breaks embedded forms

### ISSUE THREAD

**Issue by stroborobo** [Bixie/pagekit-formmaker#20]
Hi Matthijs,

with 5df8ee7d you changed how the fieldtypes get their `ajax_url` (for upload esp.). To get that value from the index.php to the frontend there's [this 'view.data' thing in index.php](https://github.com/Bixie/pagekit-formmaker/blob/5df8ee7/index.php#L120), but that only triggers for formmaker urls, not the ones where it's embedded in another site by using it's shortcode (`(formmaker){"id":"1"}`).

Maybe you could always embed that value since it's quite short, or is there a way to recognise whether the URL will load a formmaker form?

Have a good one!

**Comment by malles** [comment]
Nice catch, thanks.
Managed to squeeze it in.

**Comment by stroborobo** [comment]
Thanks!
