### ISSUE TITLE
Allow whitespaces etc. in select option

### ISSUE THREAD

**Issue by benedu** [Bixie/pagekit-formmaker#21]
Hey,

would be nice if the value of the select option would support whitespaces etc. Or at least that I could use the option string in the email template. Now only the label and the value is supported.

Clients would be happy to have an human readable value :)

https://www.w3.org/TR/html4/interact/forms.html#h-17.6

**Comment by benedu** [comment]
I just did that quick & dirty in the `replaceString()` method in src/Submission/MailHelper.php

```php
if (!empty($placeholder[1]) && $placeholder[1] === 'text') {
		foreach ($this->submission->fieldsubmissions[$placeholder[0]]['field']['options'] as $option) {
			if ($option['value'] ===  implode($arraySeparator, $this->submission->fieldsubmissions[$placeholder[0]]['value']))
				return $option['text'];
		}
}
```

**Comment by benedu** [comment]
Can just use `$$ selectname:formatted $$` to get a well formated value in the mail template.

**Comment by malles** [comment]
Great! I knew the formatted value should be somewhere available there, great that that shortcode takes it like that.
