### ISSUE TITLE
File upload link in email broken

### ISSUE THREAD

**Issue by benedu** [Bixie/pagekit-formmaker#22]
Hey,

the value of the file upload outputs only the name of the file and not the link to the file like before.

**Comment by stroborobo** [comment]
The [replacement in MailHelper][mh] are based on [Submission's fieldsubmissions][fs], which builds on [FieldValueBase's toFormattedArray][fa]. So the key we need there isn't actually 'value', but 'formatted'. Works for pulldowns as well.

[mh]: https://github.com/Bixie/pagekit-formmaker/blob/5df8ee7db56a821c61673c21129064b6d5bd7682/src/Submission/MailHelper.php#L53
[fs]: https://github.com/Bixie/pagekit-formmaker/blob/5df8ee7/src/Model/Submission.php#L121
[fa]: https://github.com/Bixie/pagekit-framework/blob/516af97/src/FieldValue/FieldValueBase.php#L102

**Comment by benedu** [comment]
``$$ uploadname:formatted $$` solved this.
