### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by benedu** [Bixie/pagekit-formmaker#23]
Hey Matthijs,

seems like some translations are missing when using `php ./pagekit framework:translate de_DE`.

I think it had to do with the formatting of code. This breaks for example:

from your framework (fieldtypes/email.vue)
```vue
<template>

    <div :class="classes(['uk-form-row'], field.data.classSfx)">
        <label :for="fieldid" class="uk-form-label" v-show="!field.data.hide_label">{{ fieldLabel | trans }}
            <a v-if="field.data.help_text && field.data.help_show == 'tooltip_icon'"
               class="uk-icon-info uk-icon-hover uk-margin-small-top uk-float-right"
               :title="field.data.help_text" data-uk-tooltip="{delay: 100}"></a>
        </label>

        <div class="uk-form-controls">
            <input type="email" class="uk-form-width-large" placeholder="{{ field.data.placeholder || '' | trans }}"
                   :name="fieldid" :id="fieldid"
                   v-model="inputValue"
                   v-validate:required="fieldRequired" v-validate:email/>

            <p v-if="field.data.help_text && field.data.help_show == 'block'"
               class="uk-form-help-block">{{{field.data.help_text}}}</p>

            <p class="uk-form-help-block uk-text-danger" v-show="fieldInvalid(form)">{{ field.data.requiredError ||
                'Please enter a value' | trans }}</p>
        </div>
    </div>

</template>
```

Without the double pipe, Pagekit is able to catch the translation `Please enter a value`

**Comment by stroborobo** [comment]
That's fixed with [6664cfed in framework](https://github.com/Bixie/pagekit-framework/commit/6664cfed987606a2baa3989cf95970246da011bf), isn't it?

**Comment by malles** [comment]
Yes it is.
For translating, use the extensions own translate command: `php pagekit formmaker:translate de_DE` and `php pagekit framework:translate de_DE`. The system translate command is only used to generate the `messages.pot` file. The extensions command adds strings from field-settings and generates the `messages.php` files for the different locales.

**Comment by benedu** [comment]
Seems like that all translations will be found :)
