### ISSUE TITLE
Form shortcode example breaking edit view

### ISSUE THREAD

**Issue by benedu** [Bixie/pagekit-formmaker#25]
Hey,

the shortcode example on the form edit view is breaking the layout. Maybe something like this would fit better:

```
(formmaker){
  "id":"",
  "hide_title":"1",
  "formStyle": "uk-form-stacked"
}
```
![image](https://cloud.githubusercontent.com/assets/14878247/13474847/2b38c440-e0c0-11e5-8445-8183dbc116d9.png)

**Comment by stroborobo** [comment]
Or an input element that selects on click. That'd be easier to use as well.
