### ISSUE TITLE
Sending E-Mail as Submitter

### ISSUE THREAD

**Issue by benedu** [Bixie/pagekit-formmaker#26]
Hey,

I think the email copy should be send in name of the one who submitted the form. Thats would make the life for the receiver much better. Because he only needs to click the "reply" button instead of copying out the email adress to reply to the form submission.

Or maybe just add a Reply-To Header to the mail, but this simple line should solve it or?

`$mail->setFrom($this->submission->email);`

https://github.com/Bixie/pagekit-formmaker/blob/master/src/Submission/MailHelper.php#L37

**Comment by malles** [comment]
I did make it an explicit setting. 
Thanks!
