### ISSUE TITLE
File Uploads Field : Permission Denied & No Submission Message

### ISSUE THREAD

**Issue by satriyowibowo** [Bixie/pagekit-formmaker#27]
can't upload file to upload fields and 
the warning says "Permission Denied"

tried to change upload dir pagekit/storage/upload-folder permission to 777 but not working
still give me the same warning

And also, after pressing 'Submit' button
on top of the form appears red warning box says '[object Object]' like this

![screenshot_384](https://cloud.githubusercontent.com/assets/6279796/13952715/76aa16e0-f06a-11e5-8fea-e35f49bbf2e7.png)

**Comment by malles** [comment]
I will have to take a look at the message. 
Did you allow access to uploads to the correct usergroups?
![image](https://cloud.githubusercontent.com/assets/5442402/13984124/87e73e30-f0f4-11e5-8b29-413ed01ee724.png)

**Comment by satriyowibowo** [comment]
yes i did, 'Anonymous' allowed to upload file(s)
![screenshot_393](https://cloud.githubusercontent.com/assets/6279796/13993402/d1479d0a-f152-11e5-968b-9e006d0e6b6e.png)

right now form submission is not working
you can check the page at hostmikro.com/tentang/payment-verification

tell me if you need to check the admin page
