### ISSUE TITLE
Hide Title

### ISSUE THREAD

**Issue by webprovide** [Bixie/pagekit-formmaker#3]
the function "Hide Title" don't work.

**Comment by malles** [comment]
Showing hiding the title works fine on the demo page. Do you still have this issue?

**Comment by ddraskov** [comment]
Submission form don't send email .

**Comment by djayko** [comment]
I've this issue too.

formmaker version: 1.2.3
pagekit: 0.9.5

php: 5.6.14-1~he.1
db: 5.5.44-37.3-log

**Comment by Eichi** [comment]
Maybe forgot to disable the title of the page were you implemented the form in?
Additionally you can implement the form with the code to hide the title (actually why? There is a option in the appearance-tab of the form).
For example:
`(formmaker){"id":"1", "hide_title":"1", "formStyle": "uk-form-stacked"}`
