### ISSUE TITLE
Cannot activate this extension

### ISSUE THREAD

**Issue by ismaelw** [Bixie/pagekit-formmaker#32]
It successfully downloads the extension but when I click on "Activate" it says it cannot be activated due to a fatal error. I use Pagekit in german language. I don't know if this could be a problem.

**Comment by Eichi** [comment]
Hi,

you have to enable the bixie framework first in the modules section of pagekit (system and modules).

But it would be better if the framework gets automatically enabled together with formmaker...

**Comment by ismaelw** [comment]
Hi Eichi

Worked like a charm. Thanks you!

**Comment by malles** [comment]
I will be changing the dependency to prevent this. Thanks @Eichi!

**Comment by funky123** [comment]
Hi, i can't click on "activate" using PHP 7.04. That might cause the issue right?
