### ISSUE TITLE
Export to csv not working

### ISSUE THREAD

**Issue by lchimaru** [Bixie/pagekit-formmaker#33]
Hi,

whenever I try to export submissions to csv, console prints following error in form-submissions.js:
`Uncaught TypeError: this.$root.resource.exports is not a function`

Pagekit 1.0.0, Formmaker 1.4.0

**Comment by lchimaru** [comment]
Any ideas what might couse such an error?

**Comment by malles** [comment]
I see some more fixes are needed in export, I'll look it through

**Comment by doubbled2** [comment]
Same problem here 

form-submissions.js?v=2c7b:406 Uncaught TypeError: this.$root.resource.export is not a function

Any ideas how to solve it?

**Comment by doubbled2** [comment]
@malles is it possible that will be fixed soon? :)

**Comment by matteoannibali** [comment]
No more submissions list! Please, fix it! thanks!
<img width="1245" alt="schermata 2016-05-06 alle 23 03 50" src="https://cloud.githubusercontent.com/assets/252208/15086110/d210abec-13de-11e6-8835-64ebc9ba9f93.png">

**Comment by ilkovic** [comment]
Problem! Please help me

![image](https://cloud.githubusercontent.com/assets/8955922/15510277/0b3a9b34-21d7-11e6-9d80-baf1dbf9e913.png)

**Comment by brbaso** [comment]
I had the same issue and get it work finally. 

In  ' formmaker/app/bundle/form-submissions.js' file change the 'created' Lifecycle Hook, around line 366 by adding a new line :
`created: function created() {
                        // added line:
			this.resource = this.$resource('api/formmaker/submission{/id}', {}, {'export': {method: 'post', url: 'api/formmaker/submission/csv'}});
                        // end added line

	                this.load();
	    },`

and change in the doExport  method, around line 406:
`
           //remove/uncomment this line:
           //this.$root.resource.export({ options: this.options }).then(function (res) {	

            // add this line				
	   this.resource.export({ options: this.options }).then(function (res) {
`

Hope this helps - I am quite new in Vue.js and Pagekit and trying to figure out how does it all work though, so the solution I found is not quite clear to me ... :)

**Comment by malles** [comment]
Fixed in 1.4.2

**Comment by brbaso** [comment]
@malles  
Thanks!.
