### ISSUE TITLE
Selectize.js + Formmaker

### ISSUE THREAD

**Issue by lchimaru** [Bixie/pagekit-formmaker#34]
Hi,

it seems selectize.js not working properly with Formmaker, selected values do not send. They're missing in $data (/packages/bixie/formmaker/src/Controller/SubmissionApiController -> saveAction()) and not seem to be present in /packages/bixie/formmaker/app/bundle/formmaker.js -> save() -> data variable, which is send through $http.post.

Correct me if I'm wrong that js send form data from mentioned js method file to mentioned php method.

**Comment by lchimaru** [comment]
Could you tell me where in js form inputs are taken to be send? Maybe just little fix is needed...

**Comment by malles** [comment]
I'm not sure what selectize.js does. Do you have a link that I could check?

**Comment by lchimaru** [comment]
It is changing select input into nice hybrid input, where user can easily add new options also. But it's just part of its capabilities ;)
[http://selectize.github.io/selectize.js/](url)

**Comment by malles** [comment]
Ah I see, a chosen like. I'd have to look at that, we'd need something like this in Pagekit..

**Comment by lchimaru** [comment]
It would be great! Anyway, could you tell me, where exactly in js code, form inputs are collected, to let me try to solve that issue?

**Comment by malles** [comment]
This is done within the Vue framework, that creates the two-way bindings between the data model and the DOM-form.
