### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by tsunamitommy** [Bixie/pagekit-formmaker#35]
form maker installs fine but when trying to enable it I get a fatal error message. Any suggestions?

**Comment by benedu** [comment]
Did you installed and enabled the [Bixie/pagekit-framework](https://github.com/Bixie/pagekit-framework)?

**Comment by Eichi** [comment]
See issue #9

**Comment by tsunamitommy** [comment]
framework installed with form maker but it is also not able to be activated. Link for framework?

**Comment by tsunamitommy** [comment]
tried downloading from bixie web site  got no pagekit extension found, have also gotten a cannot load json file error, also tried user profile ext. same errors, but portfolio ext. works fine, even with out framework. A little help would be appreciatedt

**Comment by malles** [comment]
I'm sorry, I am working on a fix. You must have downloaded the new framework already, but the extensions are not done yet. Please be a little patient, I hope to release fixes tomorrow.
