### ISSUE TITLE
input type="tel"

### ISSUE THREAD

**Issue by alekseykurylev** [Bixie/pagekit-formmaker#37]
hi, cool extension! Lacking input type="tel" and check the numbers

**Comment by malles** [comment]
Interesting idea. Checking the numbers will be hard though because every country has it's own specific format. Maybe standards can be found for that.

**Comment by Eichi** [comment]
I think checking numeric, +, -, /, ., whitespace (did I forget something?) would be enough.

**Comment by alekseykurylev** [comment]
Why for each country. The test consists of the numbers, "+", "(", ")" and gaps

**Comment by malles** [comment]
Yeah, makes sense. Maybe I'll add an option for custom regexes. I'll see what I can do :)

**Comment by benedu** [comment]
Do you have any thoughts about implementing other [HTML5 input types](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Attributes) aswell?

For example:
- range
- color
- date
- time
- number

**Comment by v4codden** [comment]
Has there been any progress on this?
