### ISSUE TITLE
Plugin code in php

### ISSUE THREAD

**Issue by alekseykurylev** [Bixie/pagekit-formmaker#38]
hi, how can I embed this code " (formmaker){"id":"1"} " in php files ???

**Comment by malles** [comment]
See this code that the plugin uses: https://github.com/Bixie/pagekit-formmaker/blob/master/src/Plugin/FormmakerPlugin.php#L33

TLDR;
`App::module('bixie/formmaker')->renderForm($app, $form_id, $options)`

**Comment by alekseykurylev** [comment]
thank you
