### ISSUE TITLE
Form error

### ISSUE THREAD

**Issue by Muadib241** [Bixie/pagekit-formmaker#39]
Hi, when I send the form I have a red error message and email not send : [object Object]

Any idea ?

Website : [http://www.maquillage-permanent-perigueux.com]

Thank's for help,

**Comment by malles** [comment]
The submission request returns a "Whoops, looks like something went wrong.". Could you switch on debug mode, so the message will be shown.

**Comment by Muadib241** [comment]
I have switch on debug mode but nothing appear, just [object Object] on red background.
You can try to send a message to see

**Comment by malles** [comment]
I still see the default error message in the request, not the debug info.

![image](https://cloud.githubusercontent.com/assets/5442402/14647745/73626590-065f-11e6-865b-94f79ec27fbd.png)

Can you see an error in the errorlog?

**Comment by Muadib241** [comment]
Log folder is empty, but I have found code in debug.db, is it can help you ?

";s:8:"relative";s:48:"packages/bixie/formmaker/src/FormmakerModule.php";s:4:"link";b:0;}s:267:"boot.Closure [ <user, prototype Closure> public method {closure} ] {
  @@ path-to-website-folder/app/system/index.php 80 - 88

  - Parameters [2] {
    Parameter #0 [ <required> $event ]
    Parameter #1 [ <required> $app ]
  }
}

**Comment by Muadib241** [comment]
someone can help me ?

**Comment by SwissResl** [comment]
I have exactly the same issue on site [https://cms.schlege.li/kontakt_feedback](https://cms.schlege.li/kontakt_feedback) as you can see:
![contact error1](https://cloud.githubusercontent.com/assets/8123304/15649512/626373a0-2672-11e6-8b7f-66121600e08e.png)
The submission is saved but no email sent:
![contact error2](https://cloud.githubusercontent.com/assets/8123304/15649528/7e307998-2672-11e6-91a0-293771ba7992.png)
it doesn't matter if I want to have an email sent or not

**Comment by daveneil** [comment]
same here. anyone manage to fix this ?

**Comment by malles** [comment]
https://github.com/Bixie/pagekit-formmaker/commit/2d7149206c870be5cf17c30b250a0ac293d338c2 fixes this error
