### ISSUE TITLE
submission

### ISSUE THREAD

**Issue by ddraskov** [Bixie/pagekit-formmaker#4]
Submission form don't send email .

**Comment by malles** [comment]
Do you mean the email to the user, or to the admin?
For the mail to the user, make sure you have a field of type email in your form, and check the "Send submission confirmation to this address" checkbox.
![image](https://cloud.githubusercontent.com/assets/5442402/10552774/81d7a6e4-7456-11e5-8b5d-bfadbbe59465.png)

When selected correctly, this will also be shown in the email tab. Here you can also provide the email address for the admin-copy of the mail.
![image](https://cloud.githubusercontent.com/assets/5442402/10552852/eceaf24c-7456-11e5-992b-0b69a79a6166.png)

**Comment by ddraskov** [comment]
In both cases I didn't get anything on email.
(user nor admin )

Pagekit Version	0.9.4
Formmaker version 1.2.3

when  tested by sending email through Pagekit settings:
System> setings> mail>SMTP or PHP mailer , both works correctly.
 

For user email I selected  checkbox ,and still got wrong message.
![pic_1](https://cloud.githubusercontent.com/assets/7072832/10560076/17823de0-7500-11e5-82e9-f17688438291.png)

![image](https://cloud.githubusercontent.com/assets/7072832/10560083/46ddfcc8-7500-11e5-8062-eb980aba1e34.png)

**Comment by malles** [comment]
Can you try unchecking and checking the checkbox at the email field, and save and try again?

**Comment by ddraskov** [comment]
I have tried  but without success.
Also I tried on a different web server ,and there also does not work.

**Comment by djayko** [comment]
HI,

same issue on my site.

I tried all this:
- set up new email field with checked and unchecked state for submission email
- i changed mail settings from pagekit twice between phpmail and smtp

submissions were saved, but there is no email at all. Not for me and and no confirmation email for the sender.

**Comment by yliefting** [comment]
Same issue here, anyone knows what's causing this problem?

**Comment by ddraskov** [comment]
- I had to manually edit the database table for submission email .
 - Send mail only works with SMTP mailer .

**Comment by yliefting** [comment]
That worked. For anyone interested: go to the table pk_formmaker_form, edit the "data" field of your form. Look for "user_email_field":"false" and set it to the slug of your email field from the table pk_formmaker_field: "user_email_field":"email". After this the user will receive an email after submitting the form.

Somehow this not not saved correctly when creating the form.

**Comment by malles** [comment]
I'll look into the selection of the email field and make it more solid. 

The mailfunction uses the core mailer, so mail from formmaker should work when the regular mail works as well. Please let me know if that is not the case.
