### ISSUE TITLE
TinyMCE editor disappear when saving a field

### ISSUE THREAD

**Issue by benedictdudel** [Bixie/pagekit-formmaker#41]
Hey,

I just installed the TinyMCE editor extension on my Pagekit installation. When saving e.g. a HTML code field, the editor will disappear afterwards. The only way to get the editor back is when you refresh the page.
Don't know if this is a problem with the TinyMCE extension or with formmaker. I also tried several other places in Pagekit but I only could reproduce it within the formmaker fields.

**Comment by malles** [comment]
I'll check that out. Haven't tried TinyMCE myself yet.

**Comment by malles** [comment]
Fixed with https://github.com/Bixie/pk-framework/commit/c8780250e3b4e7fe6b96421f818c9e937cb5f703
