### ISSUE TITLE
New language

### ISSUE THREAD

**Issue by CoOllOok** [Bixie/pagekit-formmaker#42]
Hi,
How can i add a new language ?

**Comment by benedu** [comment]
[Have a look here](https://github.com/Bixie/pagekit-formmaker/blob/master/src/Console/Commands/TranslateCommand.php#L2) and #23 

> For translating, use the extensions own translate command: php pagekit formmaker:translate de_DE and php pagekit framework:translate de_DE. The system translate command is only used to generate the messages.pot file. The extensions command adds strings from field-settings and generates the messages.php files for the different locales.

Just replace de_DE with your language.

**Comment by CoOllOok** [comment]
Great! Thank you!

**Comment by malles** [comment]
Thanks!
