### ISSUE TITLE
Can Publish module with unpublished form

### ISSUE THREAD

**Issue by MOLEDesign** [Bixie/pagekit-formmaker#45]
My site was horribly broken UNLESS I was signed in as admin. No errors showing up on Google Console

Eventually tracked this down to FORMMAKER. I had a module on my home page with a contact us form. This form however was UNPUBLISHED, but the widget was published

Suggest that the Formmaker Widget creation not show unpublished forms to prevent this occuring

**Comment by malles** [comment]
Thanks!

**Comment by MOLEDesign** [comment]
Works perfectly now

'form not found'

Super fast turnaround!
