### ISSUE TITLE
Unable to make checkbox as required field

### ISSUE THREAD

**Issue by Sulpher** [Bixie/pagekit-formmaker#49]
Dear author, 
I just been noticed there is no option to make checkbox field as required while other fields have such option.
This is important when we want to add "Agree with Terms of Use" field and awaiting user action.

I saved new checkbox filed and it is non-published. When I clicking on enable button, I get the following error: "Invalid value for required option."

I suppose this issue have appeared some due to Vue.js update, so Formmaker should be updated to meet new standards.

Regards, Eugene.

**Comment by mansensen** [comment]
I have the same problem.

**Comment by pawell3000** [comment]
Same here :)

**Comment by malles** [comment]
It proves to be quite hard. The Vue validator cannot handle checkboxes at the moment. It will only be possible if you only have one option available.

**Comment by malles** [comment]
With just one checkbox it can be provided.
The field can link to a page containing the terms that needs to be agreed with.

**Comment by mansensen** [comment]
Thank you!

**Comment by romcok** [comment]
> With just one checkbox it can be provided.
> The field can link to a page containing the terms that needs to be agreed with.

Page linking is not working. I think there is a bug.
