### ISSUE TITLE
[Mobile] Menu goes out of viewport when extension is enabled.

### ISSUE THREAD

**Issue by Mezarith** [Bixie/pagekit-formmaker#5]
As the title states, the menu dropdown decides to drop up while Formmaker is enabled. This applies to mobile devices in landscape.
![screenshot_2015-11-18-08-55-57](https://cloud.githubusercontent.com/assets/6540810/11250785/52f9ed60-8dd2-11e5-8579-6096d915ec6f.png)

![screenshot_2015-11-18-08-59-40](https://cloud.githubusercontent.com/assets/6540810/11250875/bd6985ca-8dd2-11e5-9cfb-e52fd8dac3f2.png)

But the menu drops down when the extension is disabled.
![screenshot_2015-11-18-08-58-16](https://cloud.githubusercontent.com/assets/6540810/11250851/9e575c8e-8dd2-11e5-92c6-c5d2b77f8750.png)

I've tried this on another installation, and I get the same results.

Edit: The device used in the screenshots was a Nvidia SHIELD tablet. However, this (what I assume to be) bug also occurs on my Nexus 6. Can't confirm on other devices.

**Comment by malles** [comment]
The dropdown component from UIkit suffers from a bug that makes dropdowns drop up.. Hard to say if this is related to that though.

**Comment by malles** [comment]
This will happen if you publish any extension, it is because the menu doesn't fit. I suggested a PR to fix it.
