### ISSUE TITLE
Found camelCase attribute: v-validate:minLength="minLength"

### ISSUE THREAD

**Issue by jhhazelaar** [Bixie/pagekit-formmaker#51]
When running webpack got these two errors:

      ERROR in /Users/janhenk/workspace/IlionxAcademy/packages/bixie/framework/fieldtypes/textbox/textbox.vue
    
      16 |                       v-validate:required="fieldRequired"
      17 |                       v-validate:minLength="minLength"
        |                       ^
      18 |                       v-validate:maxLength="maxLength"></textarea>
    
      Found camelCase attribute: v-validate:minLength="minLength". HTML is case-insensitive. Use v-validate:min-length="minLength" instead. Vue will automatically interpret it as camelCase in JavaScript. If this is an SVG camelCase attribute, use the .camel modifier.

    ERROR in /Users/janhenk/workspace/IlionxAcademy/packages/bixie/framework/fieldtypes/textbox/textbox.vue
    
      17 |                       v-validate:minLength="minLength"
      18 |                       v-validate:maxLength="maxLength"></textarea>
        |                       ^
      19 | 
    
      Found camelCase attribute: v-validate:maxLength="maxLength". HTML is case-insensitive. Use v-validate:max-length="maxLength" instead. Vue will automatically interpret it as camelCase in JavaScript. If this is an SVG camelCase attribute, use the .camel modifier.

Changed to:
```
v-validate:min-length="minLength"
v-validate:max-length="maxLength"
```

**Comment by malles** [comment]
Thanks
