### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'Vue.field.templates')

### ISSUE THREAD

**Issue by jhhazelaar** [Bixie/pagekit-formmaker#52]
After changing issue #51 and after a new build. Access the site on Safari (Version 9.1.1 (11601.6.17)) and got this error:

[Error] SyntaxError: Unexpected token '>'
    (anonymous function) (vue.js:2202)
[Error] TypeError: undefined is not an object (evaluating 'Vue.field.templates')
    exports (bixie-framework.js:421)
    (anonymous function) (bixie-framework.js:60)
    **webpack_require** (bixie-framework.js:20)
    (anonymous function) (bixie-framework.js:40)
    global code (bixie-framework.js:41)
[Error] TypeError: Vue.ready is not a function. (In 'Vue.ready(function () {
        window.Formmaker = new Vue(module.exports);
    })', 'Vue.ready' is undefined)
    (anonymous function) (formmaker.js:100)
    **webpack_require** (formmaker.js:20)
    (anonymous function) (formmaker.js:40)
    global code (formmaker.js:41)

On Chrome it works fine.

**Comment by malles** [comment]
That was in the bable-dependency that had that error. If you update the Pagekit repo and run npm install, it should update your npm tools and bower dependencies. Then the build should be safari proof again.
