### ISSUE TITLE
Submission list empty

### ISSUE THREAD

**Issue by EquisTango** [Bixie/pagekit-formmaker#54]
I created a simple form and in the form list I can see my form has 6 active submissions. However, when I go to the submissions list, the list is empty, I can't even see the page title or list headers, only the blue header of the PageKit back end.

Looking at the page source code in the browser, I can see raw Twig tags (in the broser!), for example: {{ item.label | trans }}.

I'm using PageKit 1.0.5 and FormMaker 1.4.2 on CentOS 7, Apache 2.4.6, PHP 7.0.9, VestaPanel.

**Comment by benedu** [comment]
See issue #47 

The tags you see aren't Twig related. As far as I know Pagekit doesn't included the template language Twig yet. The tags will get parsed by [VueJS](http://vuejs.org/)

**Comment by EquisTango** [comment]
Hey thanks! 

Re-creating the form didn't solve my problem, but knowing it's VueJS and not Twig (meaning it's browser and not server code) helped me. The problem was CloudFlare's JavaScript optimization. My bad (ashamed emoticon).

That explains why I didn't see any messages in Apache or PHP error log.

It's solved now, thanks!
