### ISSUE TITLE
Implement better resource management

### ISSUE THREAD

**Issue by jdegger** [Bixie/pagekit-formmaker#55]
At the moment, the amount of HTTP requests / loaded scripts is quite a lot. 

I refer to https://github.com/pagekit/pagekit/issues/682#issuecomment-228023623 for further information about the issue.

**Comment by malles** [comment]
Yeah, you are right.
I am expecting this to be solved on Pagekit level, I will keep an eye on that.

**Comment by malles** [comment]
The field scripts have been combined to one file now, that should help a bit :)
