### ISSUE TITLE
Plain text email is visible in source code

### ISSUE THREAD

**Issue by jdegger** [Bixie/pagekit-formmaker#57]
This really is a problem and it should be fixed soon. I am doing by best to obfuscate e-mail addresses on my website -- by using forms -- but formmaker blantantly includes the plain/text mail in the source:

```javascript
var $formmaker = {"config":{"from_address":"plaintext@mailaddress.com","
```

This really should be obfuscated or even better removed from the source. I see no reason this happens, it is not even included in the XHR going on submit.

**Comment by malles** [comment]
Should be fixed with https://github.com/Bixie/pagekit-formmaker/commit/7268984f12e3411fbbbae68f2150b6ceae5edf78

**Comment by jdegger** [comment]
Amazingly fast thanks @malles I'll test it as soon as possible

**Comment by jdegger** [comment]
There is also `"submitEmail":"another@mail.com"` visible somewhere else

**Comment by jdegger** [comment]
This is all patched up now
