### ISSUE TITLE
Bug error on clicking checkbox email field

### ISSUE THREAD

**Issue by stefanpkc** [Bixie/pagekit-formmaker#6]
This happens when you select ```Send submission confirmation to this address``` at ```/admin/formmaker/form/edit?id=1```

```
Uncaught TypeError: Cannot read property 'data' of
undefinedmodule.exports.watch.field.data.user_email
@ formmaker-email.js:116i.run
@ vue.min.js:6s
@ vue.min.js:6r
@ vue.min.js:6t
@ vue.min.js:6
```

**Comment by stefanpkc** [comment]
This is the line: https://github.com/Bixie/pagekit-formmaker/blob/master/app/fields/email.vue#L58

**Comment by malles** [comment]
related to #4, or probably the cause. I'll look into that. Thanks for reporting

**Comment by malles** [comment]
Fixed with https://github.com/Bixie/pagekit-formmaker/commit/ac81ff6755822957d14eb1da8a0b84730a8b106f
