### ISSUE TITLE
Incomplete captcha returns `[object Object]`

### ISSUE THREAD

**Issue by jpl42** [Bixie/pagekit-formmaker#60]
If user clicks submit without completing recaptcha, `[object Object]` appears above the form, which should be replaced with some 'Please complete the captcha' error. Thanks for looking at this

**Comment by claudericke** [comment]
Also experiencing this problem. Any fix or updates?

**Comment by Mrtenz** [comment]
The problem is that 'error' in formmaker.js is an object and not a string. If you change line 128 to ```this.error = this.$trans(error.data);``` it will show 'missing-input-response'. I am not sure where the $trans function is defined, but I will do a little bit more research and see if it is possible to show a normal message instead.
