### ISSUE TITLE
e-mail visible in page source for crawlers 

### ISSUE THREAD

**Issue by michidk** [Bixie/pagekit-formmaker#63]
Hey, since a few months I get tons of spam mails. 
After a little bit of research I found out why:
My site is protected by the [Cloudflare ScrapeShield](https://blog.cloudflare.com/introducing-scrapeshield-discover-defend-dete/) which basically obfuscates all emails on my site. So the email which is shown in the imprint and above the contact form, isn't the source where the crawlers got my mail from.

But while analyzing my page, I found this in the source code:
`var $formmaker = {"config":{"from_address":"MY_PRIVATE-EMAIL","recaptha_sitekey":"MY_CAPTHA_SITEKEY","submissions_per_page":20},"formitem":{"id":1,"status":1,"title":"Contact","slug":"contact","data":{"value":"","classSfx":"","user_email_field":"email","submitEmail":"SUPPORT_MAIL"`

MY_PRIVATE_EMAIL and SUPPORT_MAIL are there in plain text.
Is it possible to change that?

**Comment by malles** [comment]
This was fixed in https://github.com/Bixie/pagekit-formmaker/commit/7268984f12e3411fbbbae68f2150b6ceae5edf78, and in release since 1.4.3
