### ISSUE TITLE
OpenSSL Error messages

### ISSUE THREAD

**Issue by goodzht** [Bixie/pagekit-formmaker#64]
Loading composer repositories with package information
The "https://pagekit.com/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed

CentOS 6.5

**Comment by malles** [comment]
This has probably been a temporary composer problem, not related to this extension.
