### ISSUE TITLE
Bad SEO

### ISSUE THREAD

**Issue by FDiskas** [Bixie/pagekit-formmaker#66]
## Problem

Bad seo in google
http://i.imgur.com/ergZTWH.png

Here is the about contact form:
```html
<form id="formmaker-form" class="uk-form {{ formitem.data.formStyle }} {{ formitem.data.classSfx }}"
	  v-validator="form" @submit.prevent="save | valid" v-cloak>

	<h1 class="uk-article-title" v-if="!formitem.data.hide_title">{{ formitem.title }}</h1>

	<div class="uk-alert uk-alert-success" v-if="message" data-uk-alert>
		<a href="" class="uk-alert-close uk-close"></a>
		{{ message | trans }}</div>
	<div class="uk-alert uk-alert-danger" v-if="error" data-uk-alert>
		<a href="" class="uk-alert-close uk-close"></a>
		{{ error | trans }}</div>


	<div v-if="!thankyou">
		<fieldtypes :fields="fields"
					:model.sync="submission.data"
					:form="form"></fieldtypes>

		<recaptcha v-ref:grecaptcha v-if="formitem.data.recaptcha" :sitekey="config.recaptha_sitekey" :formitem="formitem" class="uk-margin"></recaptcha>

		<div class="uk-margin">
			<button class="uk-button uk-button-primary" type="submit">{{ formitem.data.submitButton | trans }}</button>
		</div>
	</div>
	<div v-else>{{{ thankyou }}}</div>

</form>
```

## Technical Details

- Pagekit version: 1.0.8
- Webserver: Apache
- Database: sqlite 3.8.10.2
- PHP Version: 7.0.9

**Comment by benedictdudel** [comment]
I think this problem isn't related to Formmaker. You will have the SEO problem with all addons of PageKit which are using VueJS.

You can read more about it in the offical [VueJS documentation](https://vuejs.org/v2/guide/ssr.html)

**Comment by FDiskas** [comment]
Vuejs is not used for static elements

**Comment by benedictdudel** [comment]
The problem is Google can't crawl sites which make heavily use of async JavaScript. And because Google can't parse the site correctly you see VueJS related stuff in your search result. Still not a problem of Formmaker.

**Comment by malles** [comment]
The data for the form is loaded synchronously, no extra requests are made. Most crawlers capable of javascript should be able to build the form. 
Thanks @benedictdudel for pointing to the right docs.
