### ISSUE TITLE
Responsive Form

### ISSUE THREAD

**Issue by manuescano** [Bixie/pagekit-formmaker#67]
Hello i check this extensión in my web but its not responsive and i dont see beautiful in phone browser.

http://creatidesign.com/web/contacto

I think its posible modify the code for use responsive  with Ui-Kit, for example in this web site...

http://creaticenter.com/index.php/contacto

Thanks and sorry for my english. If i can help you?

**Comment by malles** [comment]
It is caused by the use of `uk-flex` on the form container. Try it with `uk-text-center`
