### ISSUE TITLE
reCAPTCHA not centered

### ISSUE THREAD

**Issue by munishis** [Bixie/pagekit-formmaker#69]

**Comment by malles** [comment]
It's true, I have been fighting with it as well.
Using some CSS with flex center usually helps :)

**Comment by munishis** [comment]
Just usiing simple <center> tags around the shortcode worked for me, that's why I just closed it right away.

**Comment by malles** [comment]
brrrrr... The nineties called, they want `center` back :)

Try flex, it will make your world better
