### ISSUE TITLE
Uploads by non-registered users?

### ISSUE THREAD

**Issue by gppixelworks** [Bixie/pagekit-formmaker#83]
Am unable to allow non-registered to upload a file (a proposed travel photo site).  

Uploads as a registered user works fine.

Uploads by an un-registered user reports a permissions error. 

Have checked the stated directory permissions and don't see anything out of the ordinary.

Does Formmaker permit un-registered users to upload files?

Cheers in advance for any info.

**Comment by tobbexiv** [comment]
Did you grant the `bixie/pk-framework -> Upload files` permission under `User -> Roles` to anonymous users?

**Comment by gppixelworks** [comment]
Right.  I feel rather silly now.  :)

Ta for pointing out the obvious!
