### ISSUE TITLE
Add "hidden" feild

### ISSUE THREAD

**Issue by BrightdayStudio** [Bixie/pagekit-formmaker#85]
Request for a hidden field option. I need to send details of the current page they are on, so we know what they are viewing when they are submitting the form.

**Comment by tobbexiv** [comment]
As the addon seems to be discontinued at the moment, I would suggest that you use the HTML option and add the hidden field as your own html.

**Comment by BrightdayStudio** [comment]
@tobbexiv thank you! Good thinking about the HTML field :)
