### ISSUE TITLE
Can i create table with submissions?

### ISSUE THREAD

**Issue by katsil** [Bixie/pagekit-formmaker#88]
Hey, please can u help me?

Is there any way to create table with all submissions from one form? Like how to create table from mysql database?

![2018-02-23_13-56-12](https://user-images.githubusercontent.com/19670121/36590939-5b83d3b8-18a1-11e8-8a79-569158deae3f.png)

I tried to do it like this (just using mysql and php code) but nothing good were happened. If there is any way to do it please help me

**Comment by tobbexiv** [comment]
You can view them in the admin panel and also download a CSV file there.

If this does not fit your needs you should check the documentation of Pagekit to see how it the core is set up and you can access the data.
