### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Eichi** [Bixie/pagekit-formmaker#9]
Hi,

I need fields depending on values of other fields.

For example in an order form for replacements of engines:
First choose the manufacturer and afterwards show the dropdown with replacements available of this manufacturer.

I'll script it now quick n dirty because my customer needs it really fast, but I hope to have the time to implement it afterwards nicely in the formmaker extension.
So help would be great (how and on which places in the code I have to add the code) - I think it would be a nice feature for the future.

I would be glad to hear from you, thanks!

**Comment by stroborobo** [comment]
And a file upload! ;)

**Comment by malles** [comment]
Formmaker works with fieldtypes that are separate modules. From the next version on they will be based in the [Framework extension](https://github.com/Bixie/pagekit-framework/tree/master/fieldtypes). IT will be possible to add fielddtypes to the component form within your own extension, just by creating a folder fieldtypes, and registering it in the [index.php](https://github.com/Bixie/pagekit-formmaker/blob/master/index.php#L44). In that fieldtype you could create a small Vue app that manages your dependent fields.
This will be possible from the upcoming release. I hope to do that soon.
